services:
  # #  Gateway Service
  # gateway_service:
  #   container_name: gateway_service
  #   build:
  #     context: ./gateway_service
  #   ports:
  #     - "8003:8000"
  #   restart: always
  
  #  Coletor Service
  coletor_service_database:
    container_name: coletor_database
    image: postgres:13
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
    - app-coletor_service_database-data:/var/lib/postgresql/data/pgdata
  
  coletor_service:
    container_name: coletor_service
    build:
      context: ./coletor_service
    ports:
      - "8001:8000"
    restart: always
    volumes:
        - ./coletor_service:/app
    environment:
        - DATABASE_URI=postgresql://postgres:postgres@coletor_service_database:5432/postgres
    depends_on:
      - coletor_service_database

  #  Newsletter Service
  newsletter_service_database:
    container_name: newsletter_database
    image: postgres:13
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
    - app-newsletter_service_database-data:/var/lib/postgresql/data/pgdata

  newsletter_service:
    container_name: newsletter_service
    build:
      context: ./newsletter_service
    ports:
      - "8002:8000"
    restart: always
    volumes:
        - ./newsletter_service:/app
    environment:
        - DATABASE_URI=postgresql://postgres:postgres@newsletter_service_database:5432/postgres
    depends_on:
      - newsletter_service_database

volumes:
  app-newsletter_service_database-data:
  app-coletor_service_database-data:
