services:
  newsletter_service:
    container_name: newsletter_service
    build:
      context: ./newsletter_service
    restart: always
    volumes:
        - ./newsletter_service:/app
    environment:
    
        - NEWSLETTER_INTERVAL_SECONDS=1800
        
        - DATABASE_URI=postgresql://postgres:postgres@newsletter_service_database:5432/postgres
        - API_COLECTOR_URL=http://coletor_service:8000/coletor
        - MAIL_USERNAME=<EMAIL>
        - MAIL_FROM=<EMAIL>
        - MAIL_PASSWORD=<PASSWORD>
        - MAIL_SERVER=<SMTP_SERVER>
        - MAIL_PORT=<SMTP_PORT>
    depends_on:
      - newsletter_service_database
  
  coletor_service:
    container_name: coletor_service
    build:
      context: ./coletor_service
    restart: always
    volumes:
        - ./coletor_service:/app
    environment:
        - DATABASE_URI=postgresql://postgres:postgres@coletor_service_database:5432/postgres
        - OPEN_WEATHER_URL=https://api.openweathermap.org/data/2.5/weather
        - OPEN_WEATHER_API_KEY=<YOUR_API_KEY>
    depends_on:
      - coletor_service_database
  
  web_service:
    container_name: web_service
    build:
      context: ./web_service
    restart: always
    volumes:
        - ./web_service:/app
    healthcheck:
      test: HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health || exit 1
    environment:
      - BACKEND_URL=http://host.docker.internal
    depends_on:
      - coletor_service
      - newsletter_service
  
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - coletor_service
      - newsletter_service

  coletor_service_database:
    container_name: coletor_database
    image: postgres:13
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
    - app-coletor_service_database-data:/var/lib/postgresql/data/pgdata

  newsletter_service_database:
    container_name: newsletter_database
    image: postgres:13
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
    - app-newsletter_service_database-data:/var/lib/postgresql/data/pgdata

volumes:
  app-newsletter_service_database-data:
  app-coletor_service_database-data:
